-- Generated by drizzle-kit generate (drizzle-kit@0.31.10)
-- This file is auto-generated by Plan 02-01 execution.
-- Apply order: (1) this file, (2) custom/001_agency_id_immutable.sql, (3) custom/002_force_rls_and_app_role.sql
-- Do not edit manually — regenerate with: pnpm --filter=@mjagency/db db:generate

CREATE TABLE IF NOT EXISTS "agencies" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"slug" text NOT NULL,
	"name" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "agencies_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "users" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"agency_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"email" text NOT NULL,
	"role" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "sessions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"agency_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"user_id" uuid NOT NULL,
	"token_family_id" uuid NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"revoked_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "sessions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "permissions_vault" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"agency_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"permission_key" text NOT NULL,
	"encrypted_value" bytea NOT NULL,
	"key_version" integer DEFAULT 1 NOT NULL,
	"expires_at" timestamp with time zone,
	"revoked_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "permissions_vault" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "audit_log" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"occurred_at" timestamp with time zone DEFAULT now() NOT NULL,
	"table_name" text NOT NULL,
	"op" text NOT NULL,
	"row_pk" text NOT NULL,
	"actor_id" uuid,
	"agency_id" uuid NOT NULL,
	"db_user" text DEFAULT CURRENT_USER NOT NULL,
	"txid" bigint DEFAULT txid_current() NOT NULL,
	"correlation_id" text,
	"old_row" jsonb,
	"new_row" jsonb,
	"prev_hash" bytea,
	"row_hash" bytea NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "_seed_state" (
	"step_name" text PRIMARY KEY NOT NULL,
	"status" text NOT NULL,
	"started_at" timestamp with time zone,
	"completed_at" timestamp with time zone,
	"error_text" text,
	"metadata" jsonb DEFAULT '{}'::jsonb
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "users_agency_email_idx" ON "users" USING btree ("agency_id","email");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "permissions_vault_agency_key_idx" ON "permissions_vault" USING btree ("agency_id","permission_key");--> statement-breakpoint
CREATE POLICY "users_agency_isolation" ON "users" AS PERMISSIVE FOR ALL TO CURRENT_USER USING (agency_id = current_setting('app.agency_id', true)::uuid) WITH CHECK (agency_id = current_setting('app.agency_id', true)::uuid);--> statement-breakpoint
CREATE POLICY "sessions_agency_isolation" ON "sessions" AS PERMISSIVE FOR ALL TO CURRENT_USER USING (agency_id = current_setting('app.agency_id', true)::uuid) WITH CHECK (agency_id = current_setting('app.agency_id', true)::uuid);--> statement-breakpoint
CREATE POLICY "permissions_vault_agency_isolation" ON "permissions_vault" AS PERMISSIVE FOR ALL TO CURRENT_USER USING (agency_id = current_setting('app.agency_id', true)::uuid) WITH CHECK (agency_id = current_setting('app.agency_id', true)::uuid);--> statement-breakpoint
ALTER TABLE "audit_log" ADD CONSTRAINT "audit_log_op_check" CHECK (op IN ('INSERT', 'UPDATE', 'DELETE'));
