version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "payload"
      - dependency-name: "@payloadcms/*"
    open-pull-requests-limit: 10
    groups:
      opentelemetry:
        patterns:
          - "@opentelemetry/*"
      aws-sdk:
        patterns:
          - "@aws-sdk/*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
