-- Generated by scripts/gen-postgres-init.sh — do not hand-edit
-- Source template: infra/postgres/init.sql.tmpl
-- Regenerate: bash scripts/gen-postgres-init.sh
--
-- Creates 12 agency roles + databases for the MJAgency multi-tenant platform.
-- Each role owns exactly one database with SCRAM-SHA-256 password auth.
-- Passwords are sourced from environment variables (never hardcoded).
-- The 13th port slot (6444) is reserved for the M002 platform admin connection.
--
-- Security: passwords use psql \set from env vars, never literal in SQL.

-- Agency: brand
DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'brand_user') THEN
    CREATE ROLE brand_user WITH LOGIN PASSWORD 'replace-via-doppler';
  ELSE
    ALTER ROLE brand_user WITH PASSWORD 'replace-via-doppler';
  END IF;
END
$$;

SELECT 'CREATE DATABASE brand_db'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'brand_db') \gexec

GRANT ALL PRIVILEGES ON DATABASE brand_db TO brand_user;
ALTER DATABASE brand_db OWNER TO brand_user;

-- Agency: ecommerce
DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'ecommerce_user') THEN
    CREATE ROLE ecommerce_user WITH LOGIN PASSWORD 'replace-via-doppler';
  ELSE
    ALTER ROLE ecommerce_user WITH PASSWORD 'replace-via-doppler';
  END IF;
END
$$;

SELECT 'CREATE DATABASE ecommerce_db'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'ecommerce_db') \gexec

GRANT ALL PRIVILEGES ON DATABASE ecommerce_db TO ecommerce_user;
ALTER DATABASE ecommerce_db OWNER TO ecommerce_user;

-- Agency: growth
DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'growth_user') THEN
    CREATE ROLE growth_user WITH LOGIN PASSWORD 'replace-via-doppler';
  ELSE
    ALTER ROLE growth_user WITH PASSWORD 'replace-via-doppler';
  END IF;
END
$$;

SELECT 'CREATE DATABASE growth_db'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'growth_db') \gexec

GRANT ALL PRIVILEGES ON DATABASE growth_db TO growth_user;
ALTER DATABASE growth_db OWNER TO growth_user;

-- Agency: webdev
DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'webdev_user') THEN
    CREATE ROLE webdev_user WITH LOGIN PASSWORD 'replace-via-doppler';
  ELSE
    ALTER ROLE webdev_user WITH PASSWORD 'replace-via-doppler';
  END IF;
END
$$;

SELECT 'CREATE DATABASE webdev_db'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'webdev_db') \gexec

GRANT ALL PRIVILEGES ON DATABASE webdev_db TO webdev_user;
ALTER DATABASE webdev_db OWNER TO webdev_user;

-- Agency: ai
DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'ai_user') THEN
    CREATE ROLE ai_user WITH LOGIN PASSWORD 'replace-via-doppler';
  ELSE
    ALTER ROLE ai_user WITH PASSWORD 'replace-via-doppler';
  END IF;
END
$$;

SELECT 'CREATE DATABASE ai_db'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'ai_db') \gexec

GRANT ALL PRIVILEGES ON DATABASE ai_db TO ai_user;
ALTER DATABASE ai_db OWNER TO ai_user;

-- Agency: branding
DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'branding_user') THEN
    CREATE ROLE branding_user WITH LOGIN PASSWORD 'replace-via-doppler';
  ELSE
    ALTER ROLE branding_user WITH PASSWORD 'replace-via-doppler';
  END IF;
END
$$;

SELECT 'CREATE DATABASE branding_db'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'branding_db') \gexec

GRANT ALL PRIVILEGES ON DATABASE branding_db TO branding_user;
ALTER DATABASE branding_db OWNER TO branding_user;

-- Agency: strategy
DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'strategy_user') THEN
    CREATE ROLE strategy_user WITH LOGIN PASSWORD 'replace-via-doppler';
  ELSE
    ALTER ROLE strategy_user WITH PASSWORD 'replace-via-doppler';
  END IF;
END
$$;

SELECT 'CREATE DATABASE strategy_db'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'strategy_db') \gexec

GRANT ALL PRIVILEGES ON DATABASE strategy_db TO strategy_user;
ALTER DATABASE strategy_db OWNER TO strategy_user;

-- Agency: finance
DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'finance_user') THEN
    CREATE ROLE finance_user WITH LOGIN PASSWORD 'replace-via-doppler';
  ELSE
    ALTER ROLE finance_user WITH PASSWORD 'replace-via-doppler';
  END IF;
END
$$;

SELECT 'CREATE DATABASE finance_db'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'finance_db') \gexec

GRANT ALL PRIVILEGES ON DATABASE finance_db TO finance_user;
ALTER DATABASE finance_db OWNER TO finance_user;

-- Agency: engineering
DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'engineering_user') THEN
    CREATE ROLE engineering_user WITH LOGIN PASSWORD 'replace-via-doppler';
  ELSE
    ALTER ROLE engineering_user WITH PASSWORD 'replace-via-doppler';
  END IF;
END
$$;

SELECT 'CREATE DATABASE engineering_db'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'engineering_db') \gexec

GRANT ALL PRIVILEGES ON DATABASE engineering_db TO engineering_user;
ALTER DATABASE engineering_db OWNER TO engineering_user;

-- Agency: product
DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'product_user') THEN
    CREATE ROLE product_user WITH LOGIN PASSWORD 'replace-via-doppler';
  ELSE
    ALTER ROLE product_user WITH PASSWORD 'replace-via-doppler';
  END IF;
END
$$;

SELECT 'CREATE DATABASE product_db'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'product_db') \gexec

GRANT ALL PRIVILEGES ON DATABASE product_db TO product_user;
ALTER DATABASE product_db OWNER TO product_user;

-- Agency: video
DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'video_user') THEN
    CREATE ROLE video_user WITH LOGIN PASSWORD 'replace-via-doppler';
  ELSE
    ALTER ROLE video_user WITH PASSWORD 'replace-via-doppler';
  END IF;
END
$$;

SELECT 'CREATE DATABASE video_db'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'video_db') \gexec

GRANT ALL PRIVILEGES ON DATABASE video_db TO video_user;
ALTER DATABASE video_db OWNER TO video_user;

-- Agency: graphic
DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'graphic_user') THEN
    CREATE ROLE graphic_user WITH LOGIN PASSWORD 'replace-via-doppler';
  ELSE
    ALTER ROLE graphic_user WITH PASSWORD 'replace-via-doppler';
  END IF;
END
$$;

SELECT 'CREATE DATABASE graphic_db'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'graphic_db') \gexec

GRANT ALL PRIVILEGES ON DATABASE graphic_db TO graphic_user;
ALTER DATABASE graphic_db OWNER TO graphic_user;

-- End of init.sql — 12 agency databases + roles created
-- 13th slot (port 6444) reserved for M002 platform-shared admin connection
