-- Generated by scripts/gen-postgres-init.sh — do not edit.
-- Plan 01-02 created the 12-DB + 12-role bootstrap.
-- Plan 02-01 added migrations_runner role per DB (BYPASSRLS).
-- Re-generate with: bash scripts/gen-postgres-init.sh

-- ============================================================
-- Create agency databases (idempotent via DO block + \gexec)
-- ============================================================
SELECT 'CREATE DATABASE ' || quote_ident(db) || ' OWNER postgres'
FROM unnest(ARRAY['brand_db','ecommerce_db','growth_db','webdev_db','ai_db','branding_db','strategy_db','finance_db','engineering_db','product_db','video_db','graphic_db']) AS db
WHERE NOT EXISTS (
  SELECT FROM pg_database WHERE datname = db
)\gexec

-- ============================================================
-- Create per-agency roles (idempotent)
-- ============================================================

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'brand_user') THEN
    CREATE ROLE brand_user WITH LOGIN PASSWORD 'changeme_brand' NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE;
  ELSE
    ALTER ROLE brand_user WITH PASSWORD 'changeme_brand';
  END IF;
END$$;
GRANT CONNECT ON DATABASE brand_db TO brand_user;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ecommerce_user') THEN
    CREATE ROLE ecommerce_user WITH LOGIN PASSWORD 'changeme_ecommerce' NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE;
  ELSE
    ALTER ROLE ecommerce_user WITH PASSWORD 'changeme_ecommerce';
  END IF;
END$$;
GRANT CONNECT ON DATABASE ecommerce_db TO ecommerce_user;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'growth_user') THEN
    CREATE ROLE growth_user WITH LOGIN PASSWORD 'changeme_growth' NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE;
  ELSE
    ALTER ROLE growth_user WITH PASSWORD 'changeme_growth';
  END IF;
END$$;
GRANT CONNECT ON DATABASE growth_db TO growth_user;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'webdev_user') THEN
    CREATE ROLE webdev_user WITH LOGIN PASSWORD 'changeme_webdev' NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE;
  ELSE
    ALTER ROLE webdev_user WITH PASSWORD 'changeme_webdev';
  END IF;
END$$;
GRANT CONNECT ON DATABASE webdev_db TO webdev_user;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ai_user') THEN
    CREATE ROLE ai_user WITH LOGIN PASSWORD 'changeme_ai' NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE;
  ELSE
    ALTER ROLE ai_user WITH PASSWORD 'changeme_ai';
  END IF;
END$$;
GRANT CONNECT ON DATABASE ai_db TO ai_user;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'branding_user') THEN
    CREATE ROLE branding_user WITH LOGIN PASSWORD 'changeme_branding' NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE;
  ELSE
    ALTER ROLE branding_user WITH PASSWORD 'changeme_branding';
  END IF;
END$$;
GRANT CONNECT ON DATABASE branding_db TO branding_user;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'strategy_user') THEN
    CREATE ROLE strategy_user WITH LOGIN PASSWORD 'changeme_strategy' NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE;
  ELSE
    ALTER ROLE strategy_user WITH PASSWORD 'changeme_strategy';
  END IF;
END$$;
GRANT CONNECT ON DATABASE strategy_db TO strategy_user;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'finance_user') THEN
    CREATE ROLE finance_user WITH LOGIN PASSWORD 'changeme_finance' NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE;
  ELSE
    ALTER ROLE finance_user WITH PASSWORD 'changeme_finance';
  END IF;
END$$;
GRANT CONNECT ON DATABASE finance_db TO finance_user;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'engineering_user') THEN
    CREATE ROLE engineering_user WITH LOGIN PASSWORD 'changeme_engineering' NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE;
  ELSE
    ALTER ROLE engineering_user WITH PASSWORD 'changeme_engineering';
  END IF;
END$$;
GRANT CONNECT ON DATABASE engineering_db TO engineering_user;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'product_user') THEN
    CREATE ROLE product_user WITH LOGIN PASSWORD 'changeme_product' NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE;
  ELSE
    ALTER ROLE product_user WITH PASSWORD 'changeme_product';
  END IF;
END$$;
GRANT CONNECT ON DATABASE product_db TO product_user;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'video_user') THEN
    CREATE ROLE video_user WITH LOGIN PASSWORD 'changeme_video' NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE;
  ELSE
    ALTER ROLE video_user WITH PASSWORD 'changeme_video';
  END IF;
END$$;
GRANT CONNECT ON DATABASE video_db TO video_user;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'graphic_user') THEN
    CREATE ROLE graphic_user WITH LOGIN PASSWORD 'changeme_graphic' NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE;
  ELSE
    ALTER ROLE graphic_user WITH PASSWORD 'changeme_graphic';
  END IF;
END$$;
GRANT CONNECT ON DATABASE graphic_db TO graphic_user;

-- ============================================================
-- migrations_runner role + per-DB grants (Plan 02-01)
-- BYPASSRLS: used only by Plan 02-03 migration runner via port 5432
-- App roles (<slug>_user) do NOT have BYPASSRLS
-- ============================================================

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'migrations_runner') THEN
    CREATE ROLE migrations_runner WITH LOGIN PASSWORD 'changeme_migrations' BYPASSRLS;
  ELSE
    ALTER ROLE migrations_runner WITH PASSWORD 'changeme_migrations';
  END IF;
END$$;

\connect brand_db
GRANT CREATE, CONNECT ON DATABASE brand_db TO migrations_runner;
GRANT ALL ON SCHEMA public TO migrations_runner;
ALTER DEFAULT PRIVILEGES FOR ROLE migrations_runner IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO brand_user;
ALTER DEFAULT PRIVILEGES FOR ROLE migrations_runner IN SCHEMA public
  GRANT USAGE ON SEQUENCES TO brand_user;

\connect ecommerce_db
GRANT CREATE, CONNECT ON DATABASE ecommerce_db TO migrations_runner;
GRANT ALL ON SCHEMA public TO migrations_runner;
ALTER DEFAULT PRIVILEGES FOR ROLE migrations_runner IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ecommerce_user;
ALTER DEFAULT PRIVILEGES FOR ROLE migrations_runner IN SCHEMA public
  GRANT USAGE ON SEQUENCES TO ecommerce_user;

\connect growth_db
GRANT CREATE, CONNECT ON DATABASE growth_db TO migrations_runner;
GRANT ALL ON SCHEMA public TO migrations_runner;
ALTER DEFAULT PRIVILEGES FOR ROLE migrations_runner IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO growth_user;
ALTER DEFAULT PRIVILEGES FOR ROLE migrations_runner IN SCHEMA public
  GRANT USAGE ON SEQUENCES TO growth_user;

\connect webdev_db
GRANT CREATE, CONNECT ON DATABASE webdev_db TO migrations_runner;
GRANT ALL ON SCHEMA public TO migrations_runner;
ALTER DEFAULT PRIVILEGES FOR ROLE migrations_runner IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO webdev_user;
ALTER DEFAULT PRIVILEGES FOR ROLE migrations_runner IN SCHEMA public
  GRANT USAGE ON SEQUENCES TO webdev_user;

\connect ai_db
GRANT CREATE, CONNECT ON DATABASE ai_db TO migrations_runner;
GRANT ALL ON SCHEMA public TO migrations_runner;
ALTER DEFAULT PRIVILEGES FOR ROLE migrations_runner IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ai_user;
ALTER DEFAULT PRIVILEGES FOR ROLE migrations_runner IN SCHEMA public
  GRANT USAGE ON SEQUENCES TO ai_user;

\connect branding_db
GRANT CREATE, CONNECT ON DATABASE branding_db TO migrations_runner;
GRANT ALL ON SCHEMA public TO migrations_runner;
ALTER DEFAULT PRIVILEGES FOR ROLE migrations_runner IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO branding_user;
ALTER DEFAULT PRIVILEGES FOR ROLE migrations_runner IN SCHEMA public
  GRANT USAGE ON SEQUENCES TO branding_user;

\connect strategy_db
GRANT CREATE, CONNECT ON DATABASE strategy_db TO migrations_runner;
GRANT ALL ON SCHEMA public TO migrations_runner;
ALTER DEFAULT PRIVILEGES FOR ROLE migrations_runner IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO strategy_user;
ALTER DEFAULT PRIVILEGES FOR ROLE migrations_runner IN SCHEMA public
  GRANT USAGE ON SEQUENCES TO strategy_user;

\connect finance_db
GRANT CREATE, CONNECT ON DATABASE finance_db TO migrations_runner;
GRANT ALL ON SCHEMA public TO migrations_runner;
ALTER DEFAULT PRIVILEGES FOR ROLE migrations_runner IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO finance_user;
ALTER DEFAULT PRIVILEGES FOR ROLE migrations_runner IN SCHEMA public
  GRANT USAGE ON SEQUENCES TO finance_user;

\connect engineering_db
GRANT CREATE, CONNECT ON DATABASE engineering_db TO migrations_runner;
GRANT ALL ON SCHEMA public TO migrations_runner;
ALTER DEFAULT PRIVILEGES FOR ROLE migrations_runner IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO engineering_user;
ALTER DEFAULT PRIVILEGES FOR ROLE migrations_runner IN SCHEMA public
  GRANT USAGE ON SEQUENCES TO engineering_user;

\connect product_db
GRANT CREATE, CONNECT ON DATABASE product_db TO migrations_runner;
GRANT ALL ON SCHEMA public TO migrations_runner;
ALTER DEFAULT PRIVILEGES FOR ROLE migrations_runner IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO product_user;
ALTER DEFAULT PRIVILEGES FOR ROLE migrations_runner IN SCHEMA public
  GRANT USAGE ON SEQUENCES TO product_user;

\connect video_db
GRANT CREATE, CONNECT ON DATABASE video_db TO migrations_runner;
GRANT ALL ON SCHEMA public TO migrations_runner;
ALTER DEFAULT PRIVILEGES FOR ROLE migrations_runner IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO video_user;
ALTER DEFAULT PRIVILEGES FOR ROLE migrations_runner IN SCHEMA public
  GRANT USAGE ON SEQUENCES TO video_user;

\connect graphic_db
GRANT CREATE, CONNECT ON DATABASE graphic_db TO migrations_runner;
GRANT ALL ON SCHEMA public TO migrations_runner;
ALTER DEFAULT PRIVILEGES FOR ROLE migrations_runner IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO graphic_user;
ALTER DEFAULT PRIVILEGES FOR ROLE migrations_runner IN SCHEMA public
  GRANT USAGE ON SEQUENCES TO graphic_user;
