// Auto-generated by Payload's withPayload() during `next build`.
// Manually bootstrapped for Plan 05-01 with empty map (no custom components yet).
// Plan 05-02+ will add real component mappings.
import type { ImportMap } from 'payload'

export const importMap: ImportMap = {}
