/**
 * packages/cms/src/collections/media-assets.ts
 *
 * Payload 3.82.1 CollectionConfig for the `media_assets` collection.
 * Digital Asset Management (DAM) — images, video, SVG, documents.
 *
 * REQ-052: media_assets collection
 * REQ-060, REQ-061, REQ-062, REQ-063: DAM features
 * REQ-305: SVG sanitization (DOMPurify + SVGO) — hook is stubbed here; Plan 05-05 implements
 *
 * Fields:
 *   blur_hash        — 32-char BlurHash string computed at upload via `blurhash` npm (specs/media.md)
 *   dominant_color   — hex string from color-thief-node (specs/media.md)
 *   swatches         — top-3 hex array JSON from color-thief-node (specs/media.md)
 */
import type { CollectionBeforeOperationHook, CollectionConfig, Field } from 'payload'
import { collectionAccess, deleteAccess, fieldImmutable } from '../access/collection-access.js'

const AGENCY_ID_FIELD: Field = {
  name: 'agency_id',
  type: 'text',
  required: true,
  admin: { readOnly: true, position: 'sidebar' },
  access: { update: fieldImmutable },
}

/**
 * SVG sanitization stub — Plan 05-05 implements full DOMPurify + SVGO (REQ-305, CLAUDE.md §7).
 * This hook validates the MIME type and logs a warning if SVG is uploaded without sanitization.
 */
const svgSanitizeHook: CollectionBeforeOperationHook = async ({ args, operation }) => {
  if (operation !== 'create') return
  const data = args.data as Record<string, unknown> | undefined
  if (!data) return
  const mimeType = data['mimeType'] as string | undefined
  if (mimeType === 'image/svg+xml') {
    // Plan 05-05 replaces this stub with full DOMPurify + SVGO pipeline (REQ-305)
    console.warn(
      '[CMS] SVG upload detected — sanitization hook stub active. Plan 05-05 installs full DOMPurify + SVGO pipeline.'
    )
  }
}

export const mediaAssetsCollection: CollectionConfig = {
  slug: 'media_assets',
  upload: {
    staticDir: 'media',
    mimeTypes: ['image/*', 'video/*', 'application/pdf', 'image/svg+xml'],
  },
  admin: {
    useAsTitle: 'alt',
    defaultColumns: ['alt', 'status', 'agency_id', 'updatedAt'],
    group: 'Media',
  },
  access: {
    read: collectionAccess,
    create: collectionAccess,
    update: collectionAccess,
    delete: deleteAccess,
  },
  hooks: {
    beforeOperation: [svgSanitizeHook],
  },
  fields: [
    AGENCY_ID_FIELD,
    {
      name: 'alt',
      type: 'text',
      required: true,
      minLength: 10,
      maxLength: 125,
      admin: {
        description: 'Alt text is required. Minimum 10 characters, maximum 125 characters.',
      },
    },
    {
      name: 'caption',
      type: 'textarea',
    },
    {
      name: 'tags',
      type: 'array',
      fields: [
        {
          name: 'tag',
          type: 'text',
        },
      ],
    },
    {
      name: 'status',
      type: 'select',
      defaultValue: 'draft',
      options: [
        { label: 'Draft', value: 'draft' },
        { label: 'Pending Review', value: 'pending_review' },
        { label: 'Approved', value: 'approved' },
        { label: 'Published', value: 'published' },
        { label: 'Paused', value: 'paused' },
        { label: 'Archived', value: 'archived' },
        { label: 'Deleted', value: 'deleted' },
      ],
      admin: { position: 'sidebar' },
    },
    {
      name: 'blur_hash',
      type: 'text',
      admin: {
        readOnly: true,
        description:
          'BlurHash placeholder string — auto-generated at upload via `blurhash` npm (Plan 05-05 wires the pipeline).',
        position: 'sidebar',
      },
    },
    {
      name: 'dominant_color',
      type: 'text',
      admin: {
        readOnly: true,
        description:
          'Dominant color hex — extracted at upload via color-thief-node (Plan 05-05 wires the pipeline).',
        position: 'sidebar',
      },
    },
    {
      name: 'swatches',
      type: 'json',
      admin: {
        readOnly: true,
        description:
          'Top-3 color swatch hex array — extracted at upload via color-thief-node (Plan 05-05 wires the pipeline).',
      },
    },
    {
      name: 'has_captions',
      type: 'checkbox',
      defaultValue: false,
      admin: { position: 'sidebar' },
    },
    {
      name: 'caption_language',
      type: 'text',
      defaultValue: 'en',
      admin: { position: 'sidebar' },
    },
    {
      name: 'ai_generated',
      type: 'checkbox',
      defaultValue: false,
      admin: {
        position: 'sidebar',
        description: 'Mark if this asset was generated by AI. Enables compliance disclosure (REQ-207).',
      },
    },
    {
      name: 'permission_file',
      type: 'upload',
      relationTo: 'media_assets',
      admin: {
        description: 'Model release, usage rights, or permission documentation.',
      },
    },
  ],
}
