-- Phase 11: Seed platform viral patterns for Pakistani creators
-- Realistic patterns by platform, niche, and view tier

INSERT INTO public.platform_viral_patterns (platform, niche, view_tier, pattern_data, last_updated) VALUES
-- YouTube: Travel (outdoor, voiceover, location reveals)
('youtube', 'travel', '100-1k', '{"avg_motion": 62, "avg_faces": 1.2, "avg_audio_energy": 70, "avg_duration": 480, "avg_brightness": 65, "optimal_posting_hour_pkt": 20, "avg_hashtag_count": 8, "sample_count": 150, "characteristics": ["outdoor wide shots", "voiceover narration", "location reveals"]}'::jsonb, now()),
('youtube', 'travel', '1k-10k', '{"avg_motion": 68, "avg_faces": 0.8, "avg_audio_energy": 75, "avg_duration": 600, "avg_brightness": 70, "optimal_posting_hour_pkt": 19, "avg_hashtag_count": 10, "sample_count": 280, "characteristics": ["4K cinematography", "cinematic music", "transitions", "location guides"]}'::jsonb, now()),
('youtube', 'travel', '10k-100k', '{"avg_motion": 75, "avg_faces": 0.5, "avg_audio_energy": 78, "avg_duration": 720, "avg_brightness": 72, "optimal_posting_hour_pkt": 18, "avg_hashtag_count": 12, "sample_count": 420, "characteristics": ["cinematic production", "drone shots", "narrative structure", "cultural insights"]}'::jsonb, now()),
('youtube', 'travel', '100k+', '{"avg_motion": 82, "avg_faces": 0.3, "avg_audio_energy": 80, "avg_duration": 900, "avg_brightness": 75, "optimal_posting_hour_pkt": 19, "avg_hashtag_count": 15, "sample_count": 180, "characteristics": ["professional cinematography", "storytelling", "local interactions", "educational value"]}'::jsonb, now()),

-- YouTube: Hotels (short, fast-paced, multiple angles)
('youtube', 'hotels', '100-1k', '{"avg_motion": 55, "avg_faces": 2.5, "avg_audio_energy": 65, "avg_duration": 240, "avg_brightness": 75, "optimal_posting_hour_pkt": 15, "avg_hashtag_count": 6, "sample_count": 120, "characteristics": ["room tours", "quick cuts", "amenity showcase", "personal narration"]}'::jsonb, now()),
('youtube', 'hotels', '1k-10k', '{"avg_motion": 60, "avg_faces": 2.0, "avg_audio_energy": 70, "avg_duration": 300, "avg_brightness": 78, "optimal_posting_hour_pkt": 16, "avg_hashtag_count": 8, "sample_count": 250, "characteristics": ["detailed tours", "luxury aesthetic", "B-roll", "music background"]}'::jsonb, now()),
('youtube', 'hotels', '10k-100k', '{"avg_motion": 65, "avg_faces": 1.5, "avg_audio_energy": 72, "avg_duration": 360, "avg_brightness": 80, "optimal_posting_hour_pkt": 17, "avg_hashtag_count": 10, "sample_count": 380, "characteristics": ["cinematic tours", "VFX transitions", "honest reviews", "personal style"]}'::jsonb, now()),
('youtube', 'hotels', '100k+', '{"avg_motion": 70, "avg_faces": 1.0, "avg_audio_energy": 75, "avg_duration": 450, "avg_brightness": 82, "optimal_posting_hour_pkt": 18, "avg_hashtag_count": 12, "sample_count": 160, "characteristics": ["luxury production", "expert commentary", "comparison elements", "stunning cinematography"]}'::jsonb, now()),

-- YouTube: Cars (revving, movement, interior tours)
('youtube', 'cars', '100-1k', '{"avg_motion": 70, "avg_faces": 1.8, "avg_audio_energy": 80, "avg_duration": 300, "avg_brightness": 60, "optimal_posting_hour_pkt": 20, "avg_hashtag_count": 7, "sample_count": 200, "characteristics": ["engine sounds", "driving shots", "interior tour", "personal review"]}'::jsonb, now()),
('youtube', 'cars', '1k-10k', '{"avg_motion": 75, "avg_faces": 1.5, "avg_audio_energy": 82, "avg_duration": 360, "avg_brightness": 62, "optimal_posting_hour_pkt": 19, "avg_hashtag_count": 9, "sample_count": 310, "characteristics": ["acceleration clips", "4K video", "commentary", "specs overlay"]}'::jsonb, now()),
('youtube', 'cars', '10k-100k', '{"avg_motion": 80, "avg_faces": 1.0, "avg_audio_energy": 85, "avg_duration": 480, "avg_brightness": 65, "optimal_posting_hour_pkt": 20, "avg_hashtag_count": 11, "sample_count": 450, "characteristics": ["professional footage", "multiple angles", "sound design", "personality-driven"]}'::jsonb, now()),
('youtube', 'cars', '100k+', '{"avg_motion": 85, "avg_faces": 0.8, "avg_audio_energy": 87, "avg_duration": 600, "avg_brightness": 68, "optimal_posting_hour_pkt": 19, "avg_hashtag_count": 13, "sample_count": 220, "characteristics": ["cinematic car videos", "unique angles", "lifestyle shots", "production value"]}'::jsonb, now()),

-- YouTube: Bikes (similar to cars, focus on riding)
('youtube', 'bikes', '100-1k', '{"avg_motion": 72, "avg_faces": 2.0, "avg_audio_energy": 78, "avg_duration": 240, "avg_brightness": 58, "optimal_posting_hour_pkt": 18, "avg_hashtag_count": 6, "sample_count": 140, "characteristics": ["riding footage", "acceleration", "helmet cam", "personal vlog"]}'::jsonb, now()),
('youtube', 'bikes', '1k-10k', '{"avg_motion": 78, "avg_faces": 1.5, "avg_audio_energy": 80, "avg_duration": 300, "avg_brightness": 60, "optimal_posting_hour_pkt": 19, "avg_hashtag_count": 8, "sample_count": 270, "characteristics": ["POV footage", "stunt riding", "music sync", "adventure theme"]}'::jsonb, now()),
('youtube', 'bikes', '10k-100k', '{"avg_motion": 82, "avg_faces": 1.0, "avg_audio_energy": 82, "avg_duration": 420, "avg_brightness": 62, "optimal_posting_hour_pkt": 18, "avg_hashtag_count": 10, "sample_count": 390, "characteristics": ["cinematic riding", "4K drone", "slow-motion", "community focus"]}'::jsonb, now()),
('youtube', 'bikes', '100k+', '{"avg_motion": 85, "avg_faces": 0.7, "avg_audio_energy": 84, "avg_duration": 540, "avg_brightness": 65, "optimal_posting_hour_pkt": 19, "avg_hashtag_count": 12, "sample_count": 180, "characteristics": ["professional production", "technical reviews", "lifestyle content", "audience engagement"]}'::jsonb, now()),

-- YouTube: Coding (screen capture, high focus, longer content)
('youtube', 'coding', '100-1k', '{"avg_motion": 35, "avg_faces": 0.5, "avg_audio_energy": 60, "avg_duration": 600, "avg_brightness": 85, "optimal_posting_hour_pkt": 14, "avg_hashtag_count": 5, "sample_count": 100, "characteristics": ["screen recording", "code walkthrough", "explanation heavy", "educational"]}'::jsonb, now()),
('youtube', 'coding', '1k-10k', '{"avg_motion": 40, "avg_faces": 0.3, "avg_audio_energy": 65, "avg_duration": 720, "avg_brightness": 87, "optimal_posting_hour_pkt": 14, "avg_hashtag_count": 7, "sample_count": 220, "characteristics": ["tutorial format", "cursor highlighting", "clear explanation", "real-time coding"]}'::jsonb, now()),
('youtube', 'coding', '10k-100k', '{"avg_motion": 45, "avg_faces": 0.2, "avg_audio_energy": 70, "avg_duration": 900, "avg_brightness": 88, "optimal_posting_hour_pkt": 15, "avg_hashtag_count": 9, "sample_count": 350, "characteristics": ["professional setup", "project-based", "best practices", "community questions"]}'::jsonb, now()),
('youtube', 'coding', '100k+', '{"avg_motion": 50, "avg_faces": 0.1, "avg_audio_energy": 72, "avg_duration": 1200, "avg_brightness": 90, "optimal_posting_hour_pkt": 15, "avg_hashtag_count": 11, "sample_count": 140, "characteristics": ["advanced topics", "voice clarity", "production quality", "expert presenter"]}'::jsonb, now()),

-- YouTube: Lifestyle (vlogs, multiple angles, fast-paced)
('youtube', 'lifestyle', '100-1k', '{"avg_motion": 58, "avg_faces": 2.5, "avg_audio_energy": 68, "avg_duration": 360, "avg_brightness": 70, "optimal_posting_hour_pkt": 19, "avg_hashtag_count": 7, "sample_count": 180, "characteristics": ["vlog format", "personal stories", "daily life", "authentic"]}'::jsonb, now()),
('youtube', 'lifestyle', '1k-10k', '{"avg_motion": 65, "avg_faces": 2.0, "avg_audio_energy": 72, "avg_duration": 420, "avg_brightness": 72, "optimal_posting_hour_pkt": 18, "avg_hashtag_count": 9, "sample_count": 300, "characteristics": ["styled vlog", "music choices", "personality focus", "trend-aware"]}'::jsonb, now()),
('youtube', 'lifestyle', '10k-100k', '{"avg_motion": 70, "avg_faces": 1.5, "avg_audio_energy": 75, "avg_duration": 480, "avg_brightness": 74, "optimal_posting_hour_pkt": 19, "avg_hashtag_count": 11, "sample_count": 420, "characteristics": ["cinematic vlog", "lifestyle brand", "authentic storytelling", "visual consistency"]}'::jsonb, now()),
('youtube', 'lifestyle', '100k+', '{"avg_motion": 75, "avg_faces": 1.0, "avg_audio_energy": 77, "avg_duration": 600, "avg_brightness": 76, "optimal_posting_hour_pkt": 19, "avg_hashtag_count": 13, "sample_count": 200, "characteristics": ["professional production", "brand ambassadors", "trendsetter", "high-value partnerships"]}'::jsonb, now()),

-- Instagram: Travel (vertical, fast cuts, trending audio)
('instagram', 'travel', '100-1k', '{"avg_motion": 65, "avg_faces": 1.5, "avg_audio_energy": 72, "avg_duration": 30, "avg_brightness": 70, "optimal_posting_hour_pkt": 20, "avg_hashtag_count": 15, "sample_count": 200, "characteristics": ["vertical video", "trending sounds", "location tag", "quick cuts"]}'::jsonb, now()),
('instagram', 'travel', '1k-10k', '{"avg_motion": 72, "avg_faces": 1.0, "avg_audio_energy": 75, "avg_duration": 45, "avg_brightness": 72, "optimal_posting_hour_pkt": 19, "avg_hashtag_count": 18, "sample_count": 320, "characteristics": ["carousel format", "reels trending", "aesthetic filter", "location guide"]}'::jsonb, now()),
('instagram', 'travel', '10k-100k', '{"avg_motion": 78, "avg_faces": 0.7, "avg_audio_energy": 78, "avg_duration": 60, "avg_brightness": 74, "optimal_posting_hour_pkt": 18, "avg_hashtag_count": 20, "sample_count": 450, "characteristics": ["professional edit", "trending audio", "hashtag strategy", "call-to-action"]}'::jsonb, now()),
('instagram', 'travel', '100k+', '{"avg_motion": 82, "avg_faces": 0.5, "avg_audio_energy": 80, "avg_duration": 60, "avg_brightness": 76, "optimal_posting_hour_pkt": 19, "avg_hashtag_count": 22, "sample_count": 250, "characteristics": ["branded content", "influencer style", "viral potential", "commercial appeal"]}'::jsonb, now()),

-- Instagram: Hotels
('instagram', 'hotels', '100-1k', '{"avg_motion": 50, "avg_faces": 2.0, "avg_audio_energy": 65, "avg_duration": 25, "avg_brightness": 78, "optimal_posting_hour_pkt": 16, "avg_hashtag_count": 12, "sample_count": 150, "characteristics": ["room showcase", "quick tour", "aesthetic lighting", "relatable"]}'::jsonb, now()),
('instagram', 'hotels', '1k-10k', '{"avg_motion": 58, "avg_faces": 1.5, "avg_audio_energy": 70, "avg_duration": 35, "avg_brightness": 80, "optimal_posting_hour_pkt": 17, "avg_hashtag_count": 14, "sample_count": 280, "characteristics": ["luxury aesthetic", "smooth transitions", "trending sound", "honest review"]}'::jsonb, now()),
('instagram', 'hotels', '10k-100k', '{"avg_motion": 65, "avg_faces": 1.0, "avg_audio_energy": 72, "avg_duration": 50, "avg_brightness": 82, "optimal_posting_hour_pkt": 17, "avg_hashtag_count": 16, "sample_count": 400, "characteristics": ["cinematic hotel", "professional quality", "influencer partnered", "aspirational"]}'::jsonb, now()),
('instagram', 'hotels', '100k+', '{"avg_motion": 70, "avg_faces": 0.8, "avg_audio_energy": 75, "avg_duration": 60, "avg_brightness": 84, "optimal_posting_hour_pkt": 18, "avg_hashtag_count": 18, "sample_count": 180, "characteristics": ["luxury brand", "celebrity placement", "high production", "viral moments"]}'::jsonb, now()),

-- Instagram: Cars
('instagram', 'cars', '100-1k', '{"avg_motion": 68, "avg_faces": 1.5, "avg_audio_energy": 78, "avg_duration": 30, "avg_brightness": 62, "optimal_posting_hour_pkt": 20, "avg_hashtag_count": 13, "sample_count": 180, "characteristics": ["car beauty shot", "driving clips", "trending beat", "personal vibe"]}'::jsonb, now()),
('instagram', 'cars', '1k-10k', '{"avg_motion": 75, "avg_faces": 1.0, "avg_audio_energy": 80, "avg_duration": 45, "avg_brightness": 64, "optimal_posting_hour_pkt": 19, "avg_hashtag_count": 15, "sample_count": 290, "characteristics": ["acceleration clips", "smooth editing", "audio sync", "specs text"]}'::jsonb, now()),
('instagram', 'cars', '10k-100k', '{"avg_motion": 80, "avg_faces": 0.7, "avg_audio_energy": 82, "avg_duration": 55, "avg_brightness": 66, "optimal_posting_hour_pkt": 20, "avg_hashtag_count": 17, "sample_count": 420, "characteristics": ["4K footage", "professional color", "reviews narrated", "lifestyle blend"]}'::jsonb, now()),
('instagram', 'cars', '100k+', '{"avg_motion": 85, "avg_faces": 0.5, "avg_audio_energy": 84, "avg_duration": 60, "avg_brightness": 68, "optimal_posting_hour_pkt": 19, "avg_hashtag_count": 19, "sample_count": 210, "characteristics": ["cinematic cars", "brand collab", "exclusive reveals", "community voice"]}'::jsonb, now()),

-- Instagram: Bikes
('instagram', 'bikes', '100-1k', '{"avg_motion": 70, "avg_faces": 1.8, "avg_audio_energy": 76, "avg_duration": 25, "avg_brightness": 60, "optimal_posting_hour_pkt": 18, "avg_hashtag_count": 12, "sample_count": 160, "characteristics": ["riding POV", "stunt clips", "music energy", "community feel"]}'::jsonb, now()),
('instagram', 'bikes', '1k-10k', '{"avg_motion": 76, "avg_faces": 1.2, "avg_audio_energy": 78, "avg_duration": 40, "avg_brightness": 62, "optimal_posting_hour_pkt": 19, "avg_hashtag_count": 14, "sample_count": 260, "characteristics": ["adventure vibes", "trending audio", "group rides", "skill showcase"]}'::jsonb, now()),
('instagram', 'bikes', '10k-100k', '{"avg_motion": 82, "avg_faces": 0.8, "avg_audio_energy": 80, "avg_duration": 55, "avg_brightness": 64, "optimal_posting_hour_pkt": 18, "avg_hashtag_count": 16, "sample_count": 380, "characteristics": ["stunt production", "slow-mo moments", "community events", "local scenes"]}'::jsonb, now()),
('instagram', 'bikes', '100k+', '{"avg_motion": 85, "avg_faces": 0.6, "avg_audio_energy": 82, "avg_duration": 60, "avg_brightness": 66, "optimal_posting_hour_pkt": 19, "avg_hashtag_count": 18, "sample_count": 190, "characteristics": ["pro riders", "brand ambassadors", "viral stunts", "lifestyle brand"]}'::jsonb, now()),

-- Instagram: Coding
('instagram', 'coding', '100-1k', '{"avg_motion": 40, "avg_faces": 0.8, "avg_audio_energy": 60, "avg_duration": 20, "avg_brightness": 85, "optimal_posting_hour_pkt": 14, "avg_hashtag_count": 8, "sample_count": 80, "characteristics": ["code snippet visual", "quick tip", "personal brand", "educational tone"]}'::jsonb, now()),
('instagram', 'coding', '1k-10k', '{"avg_motion": 45, "avg_faces": 0.5, "avg_audio_energy": 65, "avg_duration": 30, "avg_brightness": 86, "optimal_posting_hour_pkt": 14, "avg_hashtag_count": 10, "sample_count": 180, "characteristics": ["tutorial carousel", "code walkthrough", "meme humor", "dev community"]}'::jsonb, now()),
('instagram', 'coding', '10k-100k', '{"avg_motion": 50, "avg_faces": 0.3, "avg_audio_energy": 70, "avg_duration": 45, "avg_brightness": 88, "optimal_posting_hour_pkt": 15, "avg_hashtag_count": 12, "sample_count": 300, "characteristics": ["advanced concepts", "humor integrated", "trending dev memes", "thought leadership"]}'::jsonb, now()),
('instagram', 'coding', '100k+', '{"avg_motion": 55, "avg_faces": 0.2, "avg_audio_energy": 72, "avg_duration": 60, "avg_brightness": 90, "optimal_posting_hour_pkt": 15, "avg_hashtag_count": 14, "sample_count": 120, "characteristics": ["industry insights", "conference talks", "developer advocacy", "trending topics"]}'::jsonb, now()),

-- Instagram: Lifestyle
('instagram', 'lifestyle', '100-1k', '{"avg_motion": 60, "avg_faces": 2.2, "avg_audio_energy": 70, "avg_duration": 30, "avg_brightness": 72, "optimal_posting_hour_pkt": 19, "avg_hashtag_count": 14, "avg_brightness": 72, "sample_count": 200, "characteristics": ["lifestyle moments", "trending audio", "personal story", "relatable"]}'::jsonb, now()),
('instagram', 'lifestyle', '1k-10k', '{"avg_motion": 68, "avg_faces": 1.8, "avg_audio_energy": 73, "avg_duration": 45, "avg_brightness": 74, "optimal_posting_hour_pkt": 18, "avg_hashtag_count": 16, "sample_count": 320, "characteristics": ["aesthetic lifestyle", "music choice crucial", "authentic vibes", "trend aware"]}'::jsonb, now()),
('instagram', 'lifestyle', '10k-100k', '{"avg_motion": 75, "avg_faces": 1.3, "avg_audio_energy": 76, "avg_duration": 55, "avg_brightness": 76, "optimal_posting_hour_pkt": 19, "avg_hashtag_count": 18, "sample_count": 430, "characteristics": ["curated lifestyle", "professional edit", "brand voice", "visual consistency"]}'::jsonb, now()),
('instagram', 'lifestyle', '100k+', '{"avg_motion": 80, "avg_faces": 1.0, "avg_audio_energy": 78, "avg_duration": 60, "avg_brightness": 78, "optimal_posting_hour_pkt": 19, "avg_hashtag_count": 20, "sample_count": 220, "characteristics": ["influencer style", "brand collaborations", "trendsetter", "cultural relevance"]}'::jsonb, now()),

-- Facebook: Travel
('facebook', 'travel', '100-1k', '{"avg_motion": 55, "avg_faces": 2.0, "avg_audio_energy": 65, "avg_duration": 120, "avg_brightness": 68, "optimal_posting_hour_pkt": 18, "avg_hashtag_count": 5, "sample_count": 140, "characteristics": ["shareable video", "location story", "casual narration", "group appeal"]}'::jsonb, now()),
('facebook', 'travel', '1k-10k', '{"avg_motion": 62, "avg_faces": 1.5, "avg_audio_energy": 70, "avg_duration": 180, "avg_brightness": 70, "optimal_posting_hour_pkt": 19, "avg_hashtag_count": 6, "sample_count": 260, "characteristics": ["family-friendly", "music track", "location highlight", "emotional resonance"]}'::jsonb, now()),
('facebook', 'travel', '10k-100k', '{"avg_motion": 70, "avg_faces": 1.0, "avg_audio_energy": 72, "avg_duration": 240, "avg_brightness": 72, "optimal_posting_hour_pkt": 19, "avg_hashtag_count": 7, "sample_count": 380, "characteristics": ["engaging story", "background music", "travel tips", "community engagement"]}'::jsonb, now()),
('facebook', 'travel', '100k+', '{"avg_motion": 75, "avg_faces": 0.7, "avg_audio_energy": 75, "avg_duration": 300, "avg_brightness": 74, "optimal_posting_hour_pkt": 19, "avg_hashtag_count": 8, "sample_count": 170, "characteristics": ["viral story structure", "emotional peak", "call-to-action", "shareability optimized"]}'::jsonb, now()),

-- Facebook: Hotels
('facebook', 'hotels', '100-1k', '{"avg_motion": 45, "avg_faces": 2.5, "avg_audio_energy": 60, "avg_duration": 90, "avg_brightness": 76, "optimal_posting_hour_pkt": 16, "avg_hashtag_count": 4, "sample_count": 120, "characteristics": ["room tour casual", "family-focused", "personal reaction", "budget conscious"]}'::jsonb, now()),
('facebook', 'hotels', '1k-10k', '{"avg_motion": 55, "avg_faces": 2.0, "avg_audio_energy": 65, "avg_duration": 150, "avg_brightness": 78, "optimal_posting_hour_pkt": 17, "avg_hashtag_count": 5, "sample_count": 240, "characteristics": ["detailed review", "honest feedback", "family vacation", "practical info"]}'::jsonb, now()),
('facebook', 'hotels', '10k-100k', '{"avg_motion": 62, "avg_faces": 1.5, "avg_audio_energy": 70, "avg_duration": 200, "avg_brightness": 80, "optimal_posting_hour_pkt": 17, "avg_hashtag_count": 6, "sample_count": 360, "characteristics": ["recommendation style", "value proposition", "family appeal", "booking intent"]}'::jsonb, now()),
('facebook', 'hotels', '100k+', '{"avg_motion": 70, "avg_faces": 1.0, "avg_audio_energy": 73, "avg_duration": 280, "avg_brightness": 82, "optimal_posting_hour_pkt": 18, "avg_hashtag_count": 7, "sample_count": 150, "characteristics": ["influencer review", "luxury brand", "experience showcase", "viral-worthy"]}'::jsonb, now()),

-- Facebook: Cars
('facebook', 'cars', '100-1k', '{"avg_motion": 65, "avg_faces": 1.8, "avg_audio_energy": 75, "avg_duration": 150, "avg_brightness": 60, "optimal_posting_hour_pkt": 19, "avg_hashtag_count": 4, "sample_count": 160, "characteristics": ["car beauty", "personal ownership", "casual review", "pride-focused"]}'::jsonb, now()),
('facebook', 'cars', '1k-10k', '{"avg_motion": 70, "avg_faces": 1.5, "avg_audio_energy": 78, "avg_duration": 200, "avg_brightness": 62, "optimal_posting_hour_pkt": 19, "avg_hashtag_count": 5, "sample_count": 270, "characteristics": ["feature review", "driving experience", "honest opinion", "relatability"]}'::jsonb, now()),
('facebook', 'cars', '10k-100k', '{"avg_motion": 78, "avg_faces": 1.0, "avg_audio_energy": 80, "avg_duration": 280, "avg_brightness": 64, "optimal_posting_hour_pkt": 20, "avg_hashtag_count": 6, "sample_count": 390, "characteristics": ["detailed breakdown", "value analysis", "family consideration", "purchase intent"]}'::jsonb, now()),
('facebook', 'cars', '100k+', '{"avg_motion": 82, "avg_faces": 0.7, "avg_audio_energy": 82, "avg_duration": 350, "avg_brightness": 66, "optimal_posting_hour_pkt": 19, "avg_hashtag_count": 7, "sample_count": 180, "characteristics": ["expert analysis", "market trends", "viral moment", "dealership appeal"]}'::jsonb, now()),

-- Facebook: Bikes
('facebook', 'bikes', '100-1k', '{"avg_motion": 68, "avg_faces": 2.0, "avg_audio_energy": 74, "avg_duration": 120, "avg_brightness": 58, "optimal_posting_hour_pkt": 17, "avg_hashtag_count": 4, "sample_count": 130, "characteristics": ["bike passion", "riding joy", "casual vlog", "community spirit"]}'::jsonb, now()),
('facebook', 'bikes', '1k-10k', '{"avg_motion": 75, "avg_faces": 1.5, "avg_audio_energy": 76, "avg_duration": 180, "avg_brightness": 60, "optimal_posting_hour_pkt": 18, "avg_hashtag_count": 5, "sample_count": 250, "characteristics": ["adventure vlog", "experience sharing", "safety emphasis", "community building"]}'::jsonb, now()),
('facebook', 'bikes', '10k-100k', '{"avg_motion": 80, "avg_faces": 1.0, "avg_audio_energy": 78, "avg_duration": 250, "avg_brightness": 62, "optimal_posting_hour_pkt": 18, "avg_hashtag_count": 6, "sample_count": 360, "characteristics": ["ride compilation", "stunt showcase", "group events", "loyalty building"]}'::jsonb, now()),
('facebook', 'bikes', '100k+', '{"avg_motion": 83, "avg_faces": 0.7, "avg_audio_energy": 80, "avg_duration": 320, "avg_brightness": 64, "optimal_posting_hour_pkt": 18, "avg_hashtag_count": 7, "sample_count": 170, "characteristics": ["professional riders", "brand ambassador", "viral stunts", "sponsorship appeal"]}'::jsonb, now()),

-- Facebook: Coding
('facebook', 'coding', '100-1k', '{"avg_motion": 35, "avg_faces": 0.6, "avg_audio_energy": 58, "avg_duration": 300, "avg_brightness": 84, "optimal_posting_hour_pkt": 14, "avg_hashtag_count": 3, "sample_count": 90, "characteristics": ["tutorial sharing", "learning focus", "step-by-step", "helpful resource"]}'::jsonb, now()),
('facebook', 'coding', '1k-10k', '{"avg_motion": 40, "avg_faces": 0.4, "avg_audio_energy": 62, "avg_duration": 420, "avg_brightness": 85, "optimal_posting_hour_pkt": 14, "avg_hashtag_count": 4, "sample_count": 200, "characteristics": ["detailed tutorial", "community questions", "knowledge sharing", "expertise display"]}'::jsonb, now()),
('facebook', 'coding', '10k-100k', '{"avg_motion": 45, "avg_faces": 0.2, "avg_audio_energy": 68, "avg_duration": 600, "avg_brightness": 87, "optimal_posting_hour_pkt": 15, "avg_hashtag_count": 5, "sample_count": 310, "characteristics": ["masterclass style", "industry insights", "thought leadership", "career guidance"]}'::jsonb, now()),
('facebook', 'coding', '100k+', '{"avg_motion": 50, "avg_faces": 0.1, "avg_audio_energy": 70, "avg_duration": 900, "avg_brightness": 89, "optimal_posting_hour_pkt": 15, "avg_hashtag_count": 6, "sample_count": 130, "characteristics": ["expert talks", "conference content", "industry trends", "mentorship appeal"]}'::jsonb, now()),

-- Facebook: Lifestyle
('facebook', 'lifestyle', '100-1k', '{"avg_motion": 55, "avg_faces": 2.5, "avg_audio_energy": 68, "avg_duration": 180, "avg_brightness": 70, "optimal_posting_hour_pkt": 18, "avg_hashtag_count": 5, "sample_count": 170, "characteristics": ["daily moments", "family-friendly", "relatable", "authentic"]}'::jsonb, now()),
('facebook', 'lifestyle', '1k-10k', '{"avg_motion": 62, "avg_faces": 2.0, "avg_audio_energy": 70, "avg_duration": 240, "avg_brightness": 72, "optimal_posting_hour_pkt": 19, "avg_hashtag_count": 6, "sample_count": 290, "characteristics": ["lifestyle advice", "personal brand", "music choice", "aspirational"]}'::jsonb, now()),
('facebook', 'lifestyle', '10k-100k', '{"avg_motion": 70, "avg_faces": 1.5, "avg_audio_energy": 72, "avg_duration": 300, "avg_brightness": 74, "optimal_posting_hour_pkt": 19, "avg_hashtag_count": 7, "sample_count": 400, "characteristics": ["lifestyle expert", "transformation story", "community voice", "trusted voice"]}'::jsonb, now()),
('facebook', 'lifestyle', '100k+', '{"avg_motion": 75, "avg_faces": 1.0, "avg_audio_energy": 74, "avg_duration": 360, "avg_brightness": 76, "optimal_posting_hour_pkt": 19, "avg_hashtag_count": 8, "sample_count": 190, "characteristics": ["influencer lifestyle", "brand partnerships", "cultural moments", "share-worthy stories"]}'::jsonb, now())

ON CONFLICT (platform, niche, view_tier) DO UPDATE SET
  pattern_data = EXCLUDED.pattern_data,
  last_updated = EXCLUDED.last_updated;
