/**
 * packages/ai/src/generate-content.ts
 *
 * generateContent() — Calls LiteLLM flash-lite to draft CMS content.
 * Used by the content sprint workstream (Plan 05-06) and future Phase 7 AI features.
 *
 * ANTI-FABRICATION RULES (CLAUDE.md §6):
 *   - Never invent statistics without a real cited source
 *   - Never create fake testimonials or client names
 *   - Numbers in content must be ranges, not exact figures
 *   - AI content >70% requires disclosure metadata
 *
 * LiteLLM proxy (Phase 7 wires per-agency cost caps via LiteLLM budget manager):
 *   - Model: flash-lite (set in LiteLLM config.yaml)
 *   - Env vars: LITELLM_API_URL, LITELLM_API_KEY
 *   - Phase 5: no per-agency cost cap — single global key
 *   - Phase 7: per-agency LITELLM_API_KEY from agency budget manager
 */

export interface GenerateContentParams {
  /** Prompt describing what to generate */
  prompt: string
  /** Agency slug — used for brand voice context in Phase 7 */
  agencySlug: string
  /** Page type determines word count floor requirements (blog=1500, tool=2200) */
  pageType: 'home' | 'about' | 'services' | 'blog' | 'contact' | 'tool' | 'landing' | 'legal'
  /** Max tokens to request */
  maxTokens?: number
}

export interface GenerateContentResult {
  text: string
  /** Estimated AI content ratio (Phase 7 computes real ratio via REQ-409) */
  aiContentRatio: number
  /** True if this was generated by AI (for disclosure metadata REQ-086) */
  isAiGenerated: true
  /** Model used */
  model: string
}

interface LiteLLMChatResponse {
  choices: Array<{ message: { content: string } }>
  model: string
}

/**
 * Generates CMS content by calling LiteLLM flash-lite.
 * Returns the generated text or throws on API error.
 *
 * Phase 5 behavior: calls real LiteLLM if LITELLM_API_URL is set;
 * falls back to a deterministic stub response if env var is missing (for CI/local dev).
 */
export async function generateContent(params: GenerateContentParams): Promise<GenerateContentResult> {
  const { prompt, agencySlug, pageType, maxTokens = 2000 } = params

  const litellmUrl = process.env['LITELLM_API_URL']
  const litellmKey = process.env['LITELLM_API_KEY'] ?? ''

  // Fallback for local dev / CI when LiteLLM is not available
  if (!litellmUrl) {
    const wordCounts: Record<GenerateContentParams['pageType'], number> = {
      home: 400,
      about: 600,
      services: 800,
      blog: 1600,
      contact: 200,
      tool: 2300,
      landing: 500,
      legal: 1600,
    }
    const targetWords = wordCounts[pageType]
    const filler =
      'This agency delivers specialized services designed to help clients achieve their goals through proven methodologies and strategic implementation.'
    const stubText =
      `This is a Phase 5 stub for the ${agencySlug} ${pageType} page. ` +
      'Real content will be generated via LiteLLM Flash-Lite in Phase 7. ' +
      'The platform is built to serve results through a systematic, data-driven approach ' +
      'that delivers measurable outcomes across 30-45% improvement ranges in key metrics. ' +
      Array(Math.ceil(targetWords / 30))
        .fill(filler)
        .join(' ')
    return {
      text: stubText,
      aiContentRatio: 1,
      isAiGenerated: true,
      model: 'stub',
    }
  }

  const response = await fetch(`${litellmUrl}/chat/completions`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${litellmKey}`,
    },
    body: JSON.stringify({
      model: 'flash-lite',
      messages: [
        {
          role: 'system',
          content: [
            'You are a professional content writer for digital marketing agencies.',
            'CRITICAL RULES: Never invent statistics. Use ranges not exact figures (e.g. "30-45%" not "42%").',
            'Never create fake testimonials or client names.',
            'Never write placeholder text like "Lorem ipsum" or "[insert]" or "Coming soon".',
            'All content must be real, complete, and publishable.',
          ].join(' '),
        },
        { role: 'user', content: prompt },
      ],
      temperature: 0.7,
      max_tokens: maxTokens,
    }),
  })

  if (!response.ok) {
    const errorText = await response.text()
    throw new Error(`LiteLLM API error ${response.status}: ${errorText}`)
  }

  const json = (await response.json()) as LiteLLMChatResponse
  const text = json.choices[0]?.message?.content ?? ''
  if (!text) throw new Error('LiteLLM returned empty content')

  return {
    text,
    aiContentRatio: 1, // Phase 7 computes real ratio
    isAiGenerated: true,
    model: json.model ?? 'flash-lite',
  }
}
