#!/usr/bin/env bash
# gen-pgbackrest-config.sh — Idempotent generator for pgBackRest runtime config
#
# Reads environment variables (R2 credentials + cipher pass) and renders
# infra/pgbackrest/pgbackrest.conf.tmpl into infra/pgbackrest/pgbackrest.conf
# via envsubst substitution.
#
# Usage:
#   bash scripts/gen-pgbackrest-config.sh
#   source .env && bash scripts/gen-pgbackrest-config.sh
#
# Environment variables required (in production, injected by Doppler):
#   R2_ACCOUNT_ID          — Cloudflare account ID
#   R2_ACCESS_KEY          — R2 access key ID
#   R2_SECRET_KEY          — R2 secret access key
#   PGBACKREST_CIPHER_PASS — AES-256-CBC cipher passphrase
#
# Dev behavior: if any env var is unset, substitutes __SET_VIA_DOPPLER__ placeholder.
# The generated pgbackrest.conf is structurally valid for inspection but will not
# connect to R2 in dev. This is intentional — never commit real credentials.
#
# Idempotent: re-running with the same env vars produces byte-identical output.
#
# Side effects:
#   - Sets executable bit on the three cron shell scripts.
#   - Writes infra/pgbackrest/pgbackrest.conf (overwrites if present).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
TMPL="$REPO_ROOT/infra/pgbackrest/pgbackrest.conf.tmpl"
OUT="$REPO_ROOT/infra/pgbackrest/pgbackrest.conf"
CRON_DIR="$REPO_ROOT/infra/pgbackrest/cron"

# Load .env if present and env vars not already set
if [ -f "$REPO_ROOT/.env" ]; then
  set -a
  # shellcheck disable=SC1090
  source "$REPO_ROOT/.env"
  set +a
fi

# Apply __SET_VIA_DOPPLER__ fallback for missing vars (preserves structural validity)
R2_ACCOUNT_ID="${R2_ACCOUNT_ID:-__SET_VIA_DOPPLER__}"
R2_ACCESS_KEY="${R2_ACCESS_KEY:-__SET_VIA_DOPPLER__}"
R2_SECRET_KEY="${R2_SECRET_KEY:-__SET_VIA_DOPPLER__}"
PGBACKREST_CIPHER_PASS="${PGBACKREST_CIPHER_PASS:-__SET_VIA_DOPPLER__}"

if [ ! -f "$TMPL" ]; then
  echo "ERROR: template not found: $TMPL" >&2
  exit 1
fi

echo "# Generated by scripts/gen-pgbackrest-config.sh — do not hand-edit." > "$OUT"
echo "# Re-run after Doppler injects R2 secrets in production." >> "$OUT"
echo "# Placeholder '__SET_VIA_DOPPLER__' means the env var was not set at generation time." >> "$OUT"
echo "" >> "$OUT"

# Substitute only the four pgBackRest-specific variables to avoid clobbering any
# shell-style ${VAR} references in comments. Using explicit var list is safer than
# envsubst with no arguments (which would substitute ALL env vars).
export R2_ACCOUNT_ID R2_ACCESS_KEY R2_SECRET_KEY PGBACKREST_CIPHER_PASS
envsubst '${R2_ACCOUNT_ID} ${R2_ACCESS_KEY} ${R2_SECRET_KEY} ${PGBACKREST_CIPHER_PASS}' \
  < "$TMPL" >> "$OUT"

echo "Generated: $OUT"

# Set executable bit on cron shell scripts
chmod +x "$CRON_DIR/pgbackrest-daily.sh"
chmod +x "$CRON_DIR/pgbackrest-weekly.sh"
chmod +x "$CRON_DIR/pgbackrest-monthly.sh"
echo "Set +x on cron scripts in $CRON_DIR/"

# Verify output contains expected markers
if ! grep -q "mjagency-backups" "$OUT"; then
  echo "ERROR: generation sanity check failed — 'mjagency-backups' not found in output" >&2
  exit 1
fi

echo "Verification: mjagency-backups found in $OUT — OK"

if [ "${R2_ACCOUNT_ID}" = "__SET_VIA_DOPPLER__" ]; then
  echo "Note: R2 credentials not set — pgbackrest.conf contains placeholder values."
  echo "      Run: doppler run -- bash scripts/gen-pgbackrest-config.sh  (in production)"
fi
