#!/usr/bin/env bash
# Generated by scripts/gen-postgres-init.sh — generates infra/postgres/init.sql
# Usage: bash scripts/gen-postgres-init.sh
# Requires: BRAND_DB_PASSWORD, ECOMMERCE_DB_PASSWORD, ... per-agency env vars
# OR: source .env first, then run this script.
# Output: infra/postgres/init.sql (committed; idempotent regeneration)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUTPUT="$REPO_ROOT/infra/postgres/init.sql"

# Agency slug list in canonical order (matches packages/config/src/agency-constants.ts)
AGENCIES=(brand ecommerce growth webdev ai branding strategy finance engineering product video graphic)

# Validate env vars are set (or load from .env if present)
if [ -f "$REPO_ROOT/.env" ]; then
  # shellcheck disable=SC1090
  set -a
  source "$REPO_ROOT/.env"
  set +a
fi

cat > "$OUTPUT" << 'HEADER'
-- Generated by scripts/gen-postgres-init.sh — do not hand-edit
-- Source template: infra/postgres/init.sql.tmpl
-- Regenerate: bash scripts/gen-postgres-init.sh
--
-- Creates 12 agency roles + databases for the MJAgency multi-tenant platform.
-- Each role owns exactly one database with SCRAM-SHA-256 password auth.
-- Passwords are sourced from environment variables (never hardcoded).
-- The 13th port slot (6444) is reserved for the M002 platform admin connection.
--
-- Security: passwords use psql \set from env vars, never literal in SQL.

HEADER

for slug in "${AGENCIES[@]}"; do
  UPPER="${slug^^}"
  PW_VAR="${UPPER}_DB_PASSWORD"
  PW="${!PW_VAR:-dev-secret-12345}"

  cat >> "$OUTPUT" << SQL
-- Agency: ${slug}
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${slug}_user') THEN
    CREATE ROLE ${slug}_user WITH LOGIN PASSWORD '${PW}';
  ELSE
    ALTER ROLE ${slug}_user WITH PASSWORD '${PW}';
  END IF;
END
\$\$;

SELECT 'CREATE DATABASE ${slug}_db'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${slug}_db') \gexec

GRANT ALL PRIVILEGES ON DATABASE ${slug}_db TO ${slug}_user;
ALTER DATABASE ${slug}_db OWNER TO ${slug}_user;

SQL
done

cat >> "$OUTPUT" << 'FOOTER'
-- End of init.sql — 12 agency databases + roles created
-- 13th slot (port 6444) reserved for M002 platform-shared admin connection
FOOTER

echo "Generated: $OUTPUT"
wc -l "$OUTPUT"
