#!/usr/bin/env bash
# gen-postgres-init.sh
# Generates infra/postgres/init.sql.tmpl and infra/postgres/init.sql
# from the AGENCIES list in packages/config/src/agency-constants.ts.
#
# Plan 01-02: Initial generation of 12-DB bootstrap + 12-role setup.
# Plan 02-01: Added migrations_runner role per DB (BYPASSRLS privilege).
#
# Generated by: bash scripts/gen-postgres-init.sh
# Output: infra/postgres/init.sql.tmpl (template with env var refs)
#         infra/postgres/init.sql       (dev version with placeholder passwords)
#
# Do not edit the generated files directly — re-run this script.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
OUT_TMPL="${REPO_ROOT}/infra/postgres/init.sql.tmpl"
OUT_SQL="${REPO_ROOT}/infra/postgres/init.sql"
MIGRATION_ROLE_SQL="${REPO_ROOT}/infra/postgres/migration-role.sql"

# Agency slugs in canonical order (matches packages/config/src/agency-constants.ts)
AGENCIES=(brand ecommerce growth webdev ai branding strategy finance engineering product video graphic)

# Migrations runner password — from env or placeholder for dev
MIGRATIONS_DB_PASSWORD="${MIGRATIONS_DB_PASSWORD:-changeme_migrations}"

# POSTGRES_SUPERUSER_PASSWORD — from env or placeholder for dev
POSTGRES_SUPERUSER_PASSWORD="${POSTGRES_SUPERUSER_PASSWORD:-changeme_superuser}"

generate_sql() {
  local use_placeholders="${1:-false}"
  local migrations_pw
  if [[ "$use_placeholders" == "true" ]]; then
    migrations_pw='${MIGRATIONS_DB_PASSWORD}'
  else
    migrations_pw="${MIGRATIONS_DB_PASSWORD}"
  fi

  cat <<EOF
-- Generated by scripts/gen-postgres-init.sh — do not edit.
-- Plan 01-02 created the 12-DB + 12-role bootstrap.
-- Plan 02-01 added migrations_runner role per DB (BYPASSRLS).
-- Re-generate with: bash scripts/gen-postgres-init.sh

-- ============================================================
-- Create agency databases (idempotent via DO block + \gexec)
-- ============================================================
SELECT 'CREATE DATABASE ' || quote_ident(db) || ' OWNER postgres'
FROM unnest(ARRAY[$(printf "'%s_db'" "${AGENCIES[@]}" | paste -sd ',')]) AS db
WHERE NOT EXISTS (
  SELECT FROM pg_database WHERE datname = db
)\gexec

-- ============================================================
-- Create per-agency roles (idempotent)
-- ============================================================
EOF

  for slug in "${AGENCIES[@]}"; do
    local pw_var
    if [[ "$use_placeholders" == "true" ]]; then
      pw_var="\${${slug^^}_DB_PASSWORD}"
    else
      pw_var="${!slug^^_DB_PASSWORD:-changeme_${slug}}"
    fi
    cat <<EOF

DO \$\$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${slug}_user') THEN
    CREATE ROLE ${slug}_user WITH LOGIN PASSWORD '${pw_var}' NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE;
  ELSE
    ALTER ROLE ${slug}_user WITH PASSWORD '${pw_var}';
  END IF;
END\$\$;
GRANT CONNECT ON DATABASE ${slug}_db TO ${slug}_user;
EOF
  done

  cat <<EOF

-- ============================================================
-- migrations_runner role + per-DB grants (Plan 02-01)
-- BYPASSRLS: used only by Plan 02-03 migration runner via port 5432
-- App roles (<slug>_user) do NOT have BYPASSRLS
-- ============================================================

DO \$\$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'migrations_runner') THEN
    CREATE ROLE migrations_runner WITH LOGIN PASSWORD '${migrations_pw}' BYPASSRLS;
  ELSE
    ALTER ROLE migrations_runner WITH PASSWORD '${migrations_pw}';
  END IF;
END\$\$;

EOF

  for slug in "${AGENCIES[@]}"; do
    cat <<EOF
\connect ${slug}_db
GRANT CREATE, CONNECT ON DATABASE ${slug}_db TO migrations_runner;
GRANT ALL ON SCHEMA public TO migrations_runner;
ALTER DEFAULT PRIVILEGES FOR ROLE migrations_runner IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${slug}_user;
ALTER DEFAULT PRIVILEGES FOR ROLE migrations_runner IN SCHEMA public
  GRANT USAGE ON SEQUENCES TO ${slug}_user;

EOF
  done
}

mkdir -p "$(dirname "${OUT_TMPL}")"

# Generate template version (with env var placeholders)
generate_sql "true" > "${OUT_TMPL}"
echo "[gen-postgres-init] Written: ${OUT_TMPL}"

# Generate dev version (with actual or placeholder passwords)
generate_sql "false" > "${OUT_SQL}"
echo "[gen-postgres-init] Written: ${OUT_SQL}"

# Count migrations_runner occurrences as sanity check
RUNNER_COUNT=$(grep -c "migrations_runner" "${OUT_SQL}" || true)
echo "[gen-postgres-init] migrations_runner occurrences in init.sql: ${RUNNER_COUNT}"

if [[ "${RUNNER_COUNT}" -lt 12 ]]; then
  echo "[gen-postgres-init] WARNING: Expected at least 12 migrations_runner occurrences (one per DB grant block), got ${RUNNER_COUNT}"
else
  echo "[gen-postgres-init] OK: migrations_runner role provisioned for all ${#AGENCIES[@]} agency DBs"
fi
