// scripts/generate-agency-css.ts
// Reads 12 theme.json files; emits one combined CSS file with all agency override blocks.
// Run: pnpm theme:generate
// T-04-009 mitigation: AUTO-GENERATED header warns reviewers; committed so PRs surface drift.
// REQ-044 (12 niche default themes), REQ-046 (dark overlay per agency).
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { compileThemeToCss } from '../packages/ui/src/theme/compile-theme.js';
import { assertValidTheme } from '../packages/ui/src/theme/validate-theme.js';
import type { ThemeJson } from '../packages/ui/src/theme/types.js';
import { AGENCIES } from '../packages/config/src/agency-constants.js';

const THEMES_DIR = 'packages/ui/themes/default';
const OUTPUT     = 'packages/ui/styles/agencies.generated.css';

const HEADER = `/* AUTO-GENERATED by scripts/generate-agency-css.ts.
 * DO NOT EDIT MANUALLY. Regenerate via: pnpm theme:generate
 * Source: packages/ui/themes/default/theme-{agency}.json
 * Spec: REQ-044 (12 niche default themes), REQ-046 (dark overlay)
 */
`;

function main(): void {
  const blocks: string[] = [HEADER];
  const onDisk = new Set(
    readdirSync(THEMES_DIR).filter(f => f.startsWith('theme-') && f.endsWith('.json')),
  );
  const expected = new Set(AGENCIES.map(a => `theme-${a}.json`));

  // Sanity check: 12 agencies → 12 files
  for (const exp of expected) {
    if (!onDisk.has(exp)) {
      throw new Error(`Missing theme file: ${exp}. Plan 04-04 must ship all 12.`);
    }
  }
  for (const found of onDisk) {
    if (!expected.has(found)) {
      console.warn(`  Extra file (will be included anyway): ${found}`);
    }
  }

  // Compile each agency theme to CSS
  for (const agency of AGENCIES) {
    const file = join(THEMES_DIR, `theme-${agency}.json`);
    const data = JSON.parse(readFileSync(file, 'utf-8')) as unknown;
    assertValidTheme(data, `theme-${agency}.json`);
    const css = compileThemeToCss({ agency, theme: data as ThemeJson });
    blocks.push(`/* ===== ${agency} ===== */\n${css}\n`);
  }

  writeFileSync(OUTPUT, blocks.join('\n'), 'utf-8');
  console.log(`  Generated ${OUTPUT} from ${AGENCIES.length} agency themes.`);
}

main();
