#!/usr/bin/env tsx
/**
 * scripts/migrate-rollback.ts
 *
 * Manual rollback CLI: re-applies a schema snapshot to one or all agency databases.
 *
 * Generated by: scripts/migrate-runner.ts --snapshot-before
 * Snapshot location: .snapshots/<ISO-timestamp>/
 *
 * Usage:
 *   pnpm tsx scripts/migrate-rollback.ts <snapshot-dir> [--agency=<slug>]
 *
 * WARNING: This is a destructive operation. It re-applies the schema snapshot
 * via psql -f, which will DROP and CREATE tables as specified in the snapshot.
 * See --help for the full rollback procedure and data safety notes.
 *
 * Environment:
 *   MIGRATIONS_DB_PASSWORD  (required) migrations_runner password
 */

import { spawn } from 'node:child_process'
import { readdir } from 'node:fs/promises'
import path from 'node:path'
import { AGENCIES } from '@mjagency/config'

// ---------------------------------------------------------------------------
// Help text
// ---------------------------------------------------------------------------

const HELP = `
migrate-rollback — MJAgency schema rollback tool
=================================================

Re-applies a schema snapshot (generated by --snapshot-before) to one or all
agency databases via psql. Used when a migration needs to be reversed.

DESTRUCTIVE WARNING:
  This script runs psql -f <snapshot.sql> on the target database.
  The snapshot contains DROP TABLE / CREATE TABLE statements.
  Data is preserved IF the migration that was rolled back did not itself
  drop tables or columns. If data loss is possible, restore from a full
  backup (see Plan 02-05 backup runbook) first.

Usage:
  pnpm tsx scripts/migrate-rollback.ts <snapshot-dir> [--agency=<slug>]

Arguments:
  <snapshot-dir>        Path to a snapshot directory (e.g. .snapshots/2026-04-25T...)
                        Must contain <slug>.sql files created by --snapshot-before

Options:
  --agency=<slug>       Roll back a single agency only
                        If omitted, rolls back all agencies with .sql files in the dir
  --help                Print this help and exit 0

Environment:
  MIGRATIONS_DB_PASSWORD  (required) migrations_runner password.
                          Must match the password used when the snapshot was taken.

Examples:
  # Roll back all agencies to a snapshot
  pnpm tsx scripts/migrate-rollback.ts .snapshots/2026-04-25T10-30-00-000Z

  # Roll back a single agency
  pnpm tsx scripts/migrate-rollback.ts .snapshots/2026-04-25T10-30-00-000Z --agency=ecommerce

Rollback procedure (full):
  1. Run migrate-runner with --dry-run to confirm what is pending
  2. Run migrate-runner with --snapshot-before to capture current state
  3. Apply the new migration
  4. If problems occur: run this script to restore the previous schema
  5. Restore data from backup if needed (Plan 02-05 runbook)

See: docs/runbooks/migrations.md § Snapshot + rollback procedure
`.trim()

// ---------------------------------------------------------------------------
// Argument parsing
// ---------------------------------------------------------------------------

function parseArgs(argv: string[]): {
  snapshotDir: string | undefined
  agency: string | undefined
  help: boolean
} {
  const args = argv.slice(2)
  let snapshotDir: string | undefined
  let agency: string | undefined
  let help = false

  for (const arg of args) {
    if (arg === '--help' || arg === '-h') {
      help = true
    } else if (arg.startsWith('--agency=')) {
      agency = arg.slice('--agency='.length)
    } else if (!arg.startsWith('--')) {
      snapshotDir = arg
    } else {
      console.error(`[migrate-rollback] Unknown flag: ${arg}`)
      console.error('Run with --help for usage.')
      process.exit(1)
    }
  }

  return { snapshotDir, agency, help }
}

// ---------------------------------------------------------------------------
// Rollback helpers
// ---------------------------------------------------------------------------

async function rollbackAgency(
  slug: string,
  snapshotFile: string,
  password: string
): Promise<void> {
  const args = [
    '-h', '127.0.0.1',
    '-p', '5432',
    '-U', 'migrations_runner',
    '-d', `${slug}_db`,
    '-f', snapshotFile,
    '--single-transaction', // apply entire snapshot atomically
  ]

  const env = { ...process.env, PGPASSWORD: password }

  await new Promise<void>((resolve, reject) => {
    const p = spawn('psql', args, { env, stdio: 'inherit' })
    p.on('exit', (code) => {
      if (code === 0) {
        resolve()
      } else {
        reject(
          new Error(
            `psql rollback failed for ${slug} with exit code ${code}.\n` +
              `Check that psql is in PATH, port 5432 is accessible, and the snapshot file is valid.`
          )
        )
      }
    })
    p.on('error', (err) => {
      reject(
        new Error(
          `Failed to start psql for ${slug}: ${err.message}\n` +
            `Ensure psql is installed (part of postgresql-client package).`
        )
      )
    })
  })
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  const flags = parseArgs(process.argv)

  if (flags.help) {
    console.log(HELP)
    process.exit(0)
  }

  if (!flags.snapshotDir) {
    console.error('[migrate-rollback] Missing required argument: <snapshot-dir>')
    console.error('Run with --help for usage.')
    process.exit(1)
  }

  if (flags.agency && !AGENCIES.includes(flags.agency as (typeof AGENCIES)[number])) {
    console.error(
      `[migrate-rollback] Unknown agency slug: "${flags.agency}"\n` +
        `Valid slugs: ${AGENCIES.join(', ')}`
    )
    process.exit(1)
  }

  const password = process.env.MIGRATIONS_DB_PASSWORD
  if (!password) {
    console.error(
      '[migrate-rollback] MIGRATIONS_DB_PASSWORD is not set.\n' +
        'Set it via Doppler or export it manually.\n' +
        'Run --help for details.'
    )
    process.exit(1)
  }

  const snapshotDir = path.resolve(flags.snapshotDir)

  // Determine which agencies to roll back
  let slugsToRollback: string[]
  if (flags.agency) {
    slugsToRollback = [flags.agency]
  } else {
    // Find all .sql files in snapshot dir (each file = one agency)
    const files = (await readdir(snapshotDir)).filter((f) => f.endsWith('.sql'))
    slugsToRollback = files.map((f) => f.replace('.sql', ''))
  }

  if (slugsToRollback.length === 0) {
    console.error(
      `[migrate-rollback] No .sql files found in snapshot directory: ${snapshotDir}`
    )
    process.exit(1)
  }

  console.log(
    `[migrate-rollback] Rolling back ${slugsToRollback.length} DB(s) from snapshot: ${snapshotDir}`
  )
  console.warn(
    '[migrate-rollback] WARNING: This operation re-applies the snapshot schema. ' +
      'Ensure you have a data backup before proceeding.'
  )

  let failed = 0
  for (const slug of slugsToRollback) {
    const snapshotFile = path.join(snapshotDir, `${slug}.sql`)
    try {
      console.log(`[migrate-rollback] ${slug}: applying snapshot...`)
      await rollbackAgency(slug, snapshotFile, password)
      console.log(`[migrate-rollback] ${slug}: OK`)
    } catch (err) {
      console.error(`[migrate-rollback] ${slug}: FAILED —`, err)
      failed++
    }
  }

  const total = slugsToRollback.length
  console.log(`\n[migrate-rollback] ${total - failed}/${total} OK`)

  if (failed > 0) {
    process.exit(1)
  }
}

main().catch((err) => {
  console.error('[migrate-rollback] Fatal error:', err)
  process.exit(1)
})
