#!/usr/bin/env bash
# pgbackrest-restore.sh — Operator restore tool with PITR support
#
# Restores a pgBackRest backup from R2 to the Postgres data directory.
# Supports point-in-time recovery (PITR) via --target, per-stanza selection,
# and delta restore (faster — replaces only changed files).
#
# Prerequisites:
#   - pgBackRest binary at /usr/local/bin/pgbackrest
#   - Runtime config at /etc/pgbackrest/pgbackrest.conf (generated by gen-pgbackrest-config.sh)
#   - Postgres service STOPPED before running restore
#   - Doppler injected: PGBACKREST_CIPHER_PASS, R2_ACCESS_KEY, R2_SECRET_KEY
#
# Usage:
#   bash scripts/pgbackrest-restore.sh [OPTIONS]
#
# Options:
#   --target=<TIMESTAMP>   ISO 8601 timestamp for PITR, e.g. '2026-04-26 14:30:00'
#                          If omitted, restores the latest backup.
#   --stanza=<NAME>        pgBackRest stanza name. Default: postgres-main
#   --delta                Use --delta restore (faster — replaces only diff files).
#                          Safe when restoring to the original data dir.
#   --help                 Print this help and exit 0.
#
# Examples:
#   # Restore latest backup:
#   bash scripts/pgbackrest-restore.sh
#
#   # Point-in-time recovery to a specific timestamp:
#   bash scripts/pgbackrest-restore.sh --target='2026-04-26 14:30:00'
#
#   # Faster delta restore for DR drill (staging host):
#   bash scripts/pgbackrest-restore.sh --stanza=postgres-staging --delta
#
# After restore:
#   sudo systemctl start postgresql
#   # Postgres will enter recovery mode and replay WAL up to the target time.
#
# SLA: RPO 1h, RTO 4h (PROJECT.md). PITR granularity bounded by archive_timeout=60s.

set -euo pipefail

USAGE="Usage: pgbackrest-restore.sh [--target=<TIMESTAMP>] [--stanza=<NAME>] [--delta] [--help]

  --target=<TIMESTAMP>  ISO 8601 timestamp for PITR, e.g. '2026-04-26 14:30:00'.
                        If omitted, restores latest available backup.
  --stanza=<NAME>       pgBackRest stanza name. Default: postgres-main
  --delta               Use --delta restore (faster — replaces only changed files).
                        Recommended for DR drills against a staging data dir.
  --help                Print this help and exit 0.

Examples:
  bash scripts/pgbackrest-restore.sh
  bash scripts/pgbackrest-restore.sh --target='2026-04-26 14:30:00'
  bash scripts/pgbackrest-restore.sh --stanza=postgres-staging --delta
"

STANZA="postgres-main"
TARGET=""
DELTA=""

for arg in "$@"; do
  case "$arg" in
    --target=*) TARGET="${arg#*=}" ;;
    --stanza=*) STANZA="${arg#*=}" ;;
    --delta)    DELTA="--delta" ;;
    --help)     echo "$USAGE"; exit 0 ;;
    *)          echo "Unknown argument: $arg" >&2; echo "$USAGE" >&2; exit 1 ;;
  esac
done

echo "[restore] Starting restore"
echo "[restore]   stanza  = $STANZA"
echo "[restore]   target  = ${TARGET:-<latest>}"
echo "[restore]   delta   = ${DELTA:-no}"

if [ -n "$TARGET" ]; then
  pgbackrest \
    --stanza="$STANZA" \
    --config=/etc/pgbackrest/pgbackrest.conf \
    restore \
    --target="$TARGET" \
    --target-action=promote \
    ${DELTA}
else
  pgbackrest \
    --stanza="$STANZA" \
    --config=/etc/pgbackrest/pgbackrest.conf \
    restore \
    ${DELTA}
fi

echo "[restore] Done. Postgres data dir restored."
echo "[restore] Start Postgres to bring the instance online:"
echo "[restore]   sudo systemctl start postgresql"
